#include <mpi.h> // Include MPI library
#include <iostream>
using namespace std;

int main() {
    MPI_Init(NULL, NULL); // Initialize the MPI environment

    // Declare variables
    int rank, size, n; // rank: process ID, size: total number of processes
    int localsum = 0, sum = 0; // localsum: sum of local data, sum: total sum
    int Data[15]; // Array to hold the data (generated by rank 0)
    int LocalData[5]; // Array to hold the local chunk of data for each process
    int sums[3] = { 0, 0, 0 }; // Array to store local sums gathered at rank 0

    // Get the total number of processes and the rank of the current process
    MPI_Comm_size(MPI_COMM_WORLD, &size);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    // Rank 0 generates the data array
    if (rank == 0) {
        for (int i = 0; i < 15; i++) {
            Data[i] = i+1; // Fill the array with values from 0 to 14
        }
        cout << "Data Generated." << endl;
    }
// Scatter the data array into chunks of size 5 to all processes
    MPI_Scatter(&Data, 5, MPI_INT, &LocalData, 5, MPI_INT, 0, MPI_COMM_WORLD);

    // Each process calculates the sum of its local chunk of data
    for (int i = 0; i < 5; i++) {
        localsum += LocalData[i];
    }
    cout << "Local sum = " << localsum << endl; // Print local sum for each process

    // Gather all local sums at rank 0 into the sums array
    MPI_Gather(&localsum, 1, MPI_INT, &sums, 1, MPI_INT, 0, MPI_COMM_WORLD);

    // Rank 0 calculates the total sum from all local sums
    if (rank == 0) {
        for (int i = 0; i < size; i++) { // Loop through all local sums
            sum += sums[i];
        }
        cout << "Total sum = " << sum << endl; // Print total sum
    }

    MPI_Finalize(); // Finalize the MPI environment
    return 0;
}
                